### ISSUE TITLE
Evaluation on VRD dataset

### ISSUE THREAD

**Issue by lambda-001** [yrcong/RelTR#33]
Hi. Thanks for sharing your nice work! i was wondering how to evaluate on VRD datasets?

**Comment by Pamasi** [comment]
Hi, I've used RelTr for custom datasets : the easiest way is to convert VRD dataset into coco-format and then adding a json file for the relationship  using the same structure adopted by the author i.e. `{ "train": { <image_id>: [<subject_bbox_id>, <object_bbox_id>, <relationship_id>] ...}, "test":  { <image_id>: [<subject_bbox_id>, <object_bbox_id>, <relationship_id>] ...}, "val":  { <image_id>: [<subject_bbox_id>, <object_bbox_id>, <relationship_id>] ...},  "rel_categories": { <name_of_relationship> ... } }`; otherwise you should create a custom dataset class
